### ISSUE TITLE
Builds are failing with Sphinx version issue

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/cookbook-template#154]
As of this past weekend, all Cookbook builds seem to be broken with a new version conflict.

See the nightly build [here](https://github.com/ProjectPythia/cookbook-template/actions/runs/7522839353/job/20475396357)

```
Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/sphinx/registry.py", line 438, in load_extension
    metadata = setup(app)
  File "/home/runner/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/sphinxcontrib/applehelp/__init__.py", line 230, in setup
    app.require_sphinx('5.0')
  File "/home/runner/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/sphinx/application.py", line 393, in require_sphinx
    raise VersionRequirementError(version)
sphinx.errors.VersionRequirementError: 5.0
```

**Comment by ktyle** [comment]
https://github.com/sphinx-doc/sphinxcontrib-applehelp released a new version (1.0.8) Saturday. I suspect we'll need to specify <1.0.8 for now.
